name: BUILD

on: [push]

  node:
    name: ğŸ“ Setup node & check packages install ok
    runs-on: ubuntu-latest
    steps:
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .node-version)"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: NPM Install
        run: npm install
        env:
          CI: true

  build:
    name: ğŸ›  Build
    runs-on: ubuntu-latest
    needs: [node]
    steps:
      - uses: actions/checkout@master
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
